### ISSUE TITLE
[Banking System] When you submit a bunch of transaction the server crashes

### ISSUE THREAD

**Issue by FroBoyX** [west-coast-megagames/watch-the-skies#63]
User-submitted a bunch of transactions in sequence and the server crashed.

**Comment by FroBoyX** [comment]
It should no longer be possible to submit a bunch all at once.

**Comment by Goldfox64** [comment]
This looks to be fixed.
Mass spamming the button dose not seem to crash the server, and mass transactions cant be easily done due to the new window used for the setup.

**Comment by FroBoyX** [comment]
Awesome, thanks @Goldfox64.
