### ISSUE TITLE
Negative Money Transfers.

### ISSUE THREAD

**Issue by Goldfox64** [west-coast-megagames/watch-the-skies#68]
(Issue may be known, but i don't see it reported)

You can put any of your budgets into the negative By:
Setting up a money transfer from an account with positive money, selecting the numeric value of the transfer then swapping out the sending account with one that dose not have enough to fulfill the transfer.  
It adds that cash to the receiving end put the sending end into the negative.

Bonus: I think you can crash out the sever by doing the same steps above but select the negative account to send a positive number to itself.

**Comment by FroBoyX** [comment]
I believe this bug was handled by zeroing out the money transfer. Can you confirm @Goldfox64?

**Comment by Goldfox64** [comment]
Looks like it has been fixed, it blanks out the money filed when changing accounts, so unable to pull from accounts with less money then requested.
