### ISSUE TITLE
Blank Aircraft Status Change

### ISSUE THREAD

**Issue by Goldfox64** [west-coast-megagames/watch-the-skies#72]
Under `Global Ex-Com Information` if you deploy all your aircraft then go to deploy another aircraft the `Scramble Aircraft' Filed is blank (as all aircraft are in use) But you can still select a Mission Type and Submit. That will change the Status of the last aircraft you deployed.

**Comment by FroBoyX** [comment]
Should be fixed in the latest update.

**Comment by Goldfox64** [comment]
Tested.
Can not select a blank aircraft any more.
Fixed.
