### ISSUE TITLE
[Banking System] - Same account-to-account transfers crash server.

### ISSUE THREAD

**Issue by Goldfox64** [west-coast-megagames/watch-the-skies#79]
Transferring money between same accounts causes the server to crash.

**Comment by FroBoyX** [comment]
@SMcMann, any chance you can build a moat around banking to ensure a user can't submit a transfer to the same account... I'll do the same on the front-end?

**Comment by SMcMann** [comment]
okiday

**Comment by FroBoyX** [comment]
@SMcMann solved this issue but didn't close the ticket.
