### ISSUE TITLE
Transfer Text Capitlization

### ISSUE THREAD

**Issue by Vojoc** [west-coast-megagames/watch-the-skies#83]
The text for "withdrawal Account" should have a capital "W"

**Comment by Vojoc** [comment]
Sensory "enhancers" in research has the same problem.

**Comment by Vojoc** [comment]
Anti-"satellite" Weapon Systems same problem.

**Comment by FroBoyX** [comment]
Fixed all three capitalization issues, if you find more please let me know @Vojoc!
