### ISSUE TITLE
[Global Ops] Certain Zones Stuck in Perpetual Loading

### ISSUE THREAD

**Issue by Vojoc** [west-coast-megagames/watch-the-skies#99]
In Global Military Operations, the following zones are stuck perpetually loading:

Low Earth Orbit
Mid Earth Orbit
High Earth Orbit
Lunar Orbit
Antarctica

**Comment by SMcMann** [comment]
It's actually that there is nothing to load, so the spinner is just a place-holder

**Comment by Vojoc** [comment]
Great. A lot better than infinite loading.
